version: "3.4"

services:
  catalog-api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "42000:80"

  catalog-postgres-db:
    container_name: postgres-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: